title: Open 5G Forum - Fall 2021
description: >-
  Open 5G Forum - A virtual event on open and open source software for 5G - Fall 2021 edition (RAN software)
baseurl: "/open-5g-forum" # the subpath of your site, e.g. /blog
url: "https://open5g.info" # the base hostname & protocol for your site, e.g. https://example.com

# Build settings
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js
  - jekyll-theme-conference.gemspec
  - vendor

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:

  # Language
  lang: en

  # Show theme errors:
  show_errors: false

  # Navigation bar
  navigation:
    logo:
      name: Northeastern WIoT
      img: 'NU_IoT_NLuxPlus_BRBB.png'
      url: 'https://www.northeastern.edu/wiot/'
    links:
      - name: Program
        relative_url: /program/
      - name: Talks
        relative_url: /talks/
      - name: Speakers
        relative_url: /speakers/
      - name: Registration
        disabled: true
        absolute_url: https://northeastern.zoom.us/meeting/register/tJUqce2tqzkiGNTo_xYruezi5Vv_A8O7rnug
      - name: About
        relative_url: /about/
      # - name: Future Editions
      #   menu:
      #     - name: 2021 (current)
      #       disabled: true
      #     - name: 2019
      #       relative_url: /2019/
      #     - name: 2018
      #       relative_url: /2018/

  # Main landing page
  main:
    # logo:
    #   img: ''
    links:
      - name: Program
        relative_url: /program/
      - name: Registration
        disabled: true
        absolute_url: https://northeastern.zoom.us/meeting/register/tJUqce2tqzkiGNTo_xYruezi5Vv_A8O7rnug

  # Information boxes
  info_bars:
    - title: Welcome to the Open 5G Forum website!
      color: primary
      main_only: true
      text: |
        The Open 5G Forum is a virtual event on open and open source software for the 5G ecosystem. 
        The Fall 2021 edition focuses on RAN software, with talks and tutorials on the major
        open and open source projects for programmable, virtualized, and software-defined RANs.

        The event will include hands-on tutorials that will demonstrate how to use open source 
        RAN software on [Colosseum](https://northeastern.edu/colosseum/), the world's largest hardware-in-the-loop wireless network 
        emulator.

    # - text: This is just some random content for demonstration purposes.
    #   color: warning
    #   pages_only: false

  # Live indications
  live:
    date: 01.01.2020
    timezone: GMT+1
    time_stop: 240      # in minutes
    streaming:
      time_pause:   60  # in minutes
      time_prepend:  5  # in minutes
      time_extend:   5  # in minutes
    demo: false

  talks:
    # Talk categories
    main_categories:
      - name: Keynote
        color: info
      - name: Tutorial
        color: success
      - name: Short Talks
        color: secondary
      - name: Panel
        color: info

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  # location:
  #   # URL of location / room overview page
  #   url: '/location'

  #   # Disable links to locations
  #   hide: true
  #   map:
  #     # show map
  #     enable: true
  #     # initial map center point
  #     home_coord: 47.37808, 8.53935
  #     # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
  #     # The following do match the Bootstrap design not too badly:
  #     #   - Hydda.Full
  #     #   - Thunderforest.Neighbourhood
  #     #   - Esri.WorldTopoMap
  #     map_provider: "OpenStreetMap.Mapnik"
  #     default_zoom: 17

  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true
